[package]
name = "decklink_output"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
libc = "0.2"
anyhow = "1"
image = "0.25"
common_io = { path = "../common_io" }

[build-dependencies]
cc = "1"
