[input]
device     = 0
format     = "1080p59.94"
pixfmt     = "YUV422_8"
colorspace = "BT709"

[preprocess]
size  = [512, 512]
fp16  = true
color = "BT709"

[inference]
backend = "tensorrt"
engine  = "models/yolov5s_fp16.plan"
device  = 0

[postprocess]
conf_thresh = 0.25
nms_thresh  = 0.45
tracking    = "sort"

[overlay]
font_px    = 22
show_score = true

[output]
mode      = "decklink_key"
key_level = 255
