[package]
name = "telemetry"
version = "0.1.0"
edition = "2021"

[features]
default = ["human-log"]
human-log = []
json = []
stats = []
cuda-events = []

[dependencies]
common_io = { path = "../common_io" }
